services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kakarot
      - MONGO_INITDB_ROOT_PASSWORD=pass1828!
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=kakarot
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass1828!
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo: {}